### PR TITLE
QPID-8469: [Broker-J][Message Store] The message is already cleaned when the delete listener is called

### PR DESCRIPTION
**Pull request by overmeulen**

### CODE REVIEW

**Comment by alex-rufous** [comment]
Hi Olivier,
Thanks for submitting this pull request.

Though, an invocation of message listener immediately after message removal looks like the right thing to do, could you please expand a bit more on the reasons behind this change?  Could you please add a description to the JIRA?

Kind Regards,
Alex

**Comment by overmeulen** [comment]
Thanks Alex,

I added a description in the JIRA ticket.
To make it short, we want to use the delete listener to implement the Claim-Check pattern.

Olivier

**Comment by overmeulen** [comment]
If I'm not mistaken, this fix has been merged in master, should we close this PR ?

**Comment by alex-rufous** [comment]
Hi Olivier,

You are right. The changes have been committed. Please close the PR.

Kind Regards,
Alex

**Pull request closed without merging**
