### PR TITLE
QPID-8367 [Broker-J] Trusted CA revocation list

### PR DESCRIPTION
**Pull request by vavrtom**
* added revocation functionality
* custom CRL file can be added to truststore
* if custom CRL is defined in truststore then custom CRL file will be used instead of URI in certificate's CRLDistributionPoints
* reworked test certificates generation, it uses openssl instead of certutil

### CODE REVIEW

**Comment by alex-rufous** [comment]
Hi Tomas,
I looked through the proposed changes. Please find below my review comments.

I like the idea of generation test resources on running the tests rather than having them pre-created in advance and regenerating CA, certificates, keystores, truststores, etc periodically. In fact, I started to use in my recent tests `SSLUtil#generateSelfSignedCertificate`  for certificate generation  in order to avoid relying on static test resources. My intention was to replace keystore/truststore test resources with auto-generated ones where it is possible.

Though, java API does not allow to generate all required test resources programmatically. Thus, the external utilities like openssl or NSS certutil has to be used. I am OK with your changes to switch from NSS certutil to openssl. Though, I still would like to keep the ability to run the unit and system tests on Windows platforms. Thus, I think, that we need to check the platform/environment and skip the tests relying on certificate generation with openssl. 

Potentially, we can try running the generation script and on successful execution we can write the generation status in some status file. When generation is not successful, the unit and system tests can check the file and set the flag to skip tests relying on generated resources. What do you think about it?

I have not run the tests with the changes. How long does it take to generate the test resources with openssl? If it a matter of seconds, that should be acceptable. Otherwise, we might need a mechanism to reduce the number of ssl resource generations.

Taking that you started running certificate generation script from  qpid-test-utils/pom.xml, I think it make sense to move all required ssl test resources (including generation script) into `qpid-test-utils` and drop test_resources/ssl in order to have test dependencies in one module. Potentially, the test certificate, keystores, truststores can be generated in corresponding module "target" folder and the file locations can be either relative to target folder or exposed to the unit/system tests in some way (for example, via status file).

The script is executed in maven phase `generate-resources`. I believe, that the phase should be changed to `generate-test-resources`. 

As for the implementation changes, please find my code review comments below.

The self descriptive attribute names are preferred over abbreviations and acronyms.
Thus, I would suggest to rename the new  attributes as follows:

- revocation -> certificateRevocationCheckEnabled
- crlUrl -> certificateRevocationListUrl
- onlyEndEntity -> certificateRevocationCheckOfEndEntityCertificates or checkRevocationStatusOfEndEntityCertificates
- preferCrls -> preferCertificateRevocationList[ForCertificateRevocationCheck] (I am not sure about this name)
- noFallback -> certificateRevocationCheckWithNoFallback
- softFail -> certificateRevocationCheckWithIgnoringSoftFailures

Please feel free to change the attribute name to more user friendlier names. I am not sure that my names suggested above are that good.

The crlUrl seems only allows file URLs. Why data URLs are not allowed? Is it due to security consideration? Could you please expand on it?

AuthenticationTest comments:
 AuthenticationTest uses "com.sun.net.httpserver.HttpServer". Why jetty http server cannot be used instead?
 I am not big fan of hardcoding of the test ports, as they could be occupied on the environment where tests are run, but, I see the reason why it was done.
 Perhaps, in order to avoid seeing failed tests due to port being occupied by other process, I might make sense to skip the test if http server fails to bind to the pre-defined port.

Another way to workaround this issue is by starting http server first, and than generating the ssl test resources against the http server port. For example, you can implement "org.junit.rules.ExternalResource" where you can start/stop the http server and execute the script after server startup by using java API `java.lang.ProcessBuilder`. That would eliminate the need to execute the generation script from maven. You can have a look into implementation of `EmbeddedKdcResource` which I added for KerberosAuthenticationManagerTest, etc. 

A new base class KeyStoreTestBase does not bring much value. I think it would be better to introduce utility class KeyStoreTestUtils with some static methods like checkExceptionThrownDuringKeyStoreCreation and call the utility static methods from other test classes.

TlsTest & TestSSLConstants
Unix file separator is explicitly hard-coded into test constant. I prefer environment neutral implementation.

Are you planning to add documentation for the new functionality into Qpid broker docbook module?

Kind Regards,
Alex

**Comment by bickelj** [comment]
> java API does not allow to generate all required test resources programmatically. Thus, the external utilities like openssl or NSS certutil has to be used

The use of SSLContext (part of Java API) in new TLS-related method signatures combined with alternative providers from BouncyCastle at test-time can help.

**Comment by alex-rufous** [comment]
Tomas,
I created JIRA [QPID-8402](https://issues.apache.org/jira/browse/QPID-8402) to use Bouncy Castle API for generation of self signed certificates. I already attached a couple of patches to switch from certificate generation using {{SSLUtil#generateSelfSignedCertificate}} to Bouncy Castle  alternative. I will try to add more functionality to replace pre-generated resources with ones generated on the fly. The work is in progress... I do not have a tentative date when I can finish it. I will create a pull request when I will have a better idea about Bouncy Castle capabilities.

I am not sure whether Bouncy Castle can be used for generation of all resources introduces in this pull request. Could you please have a look?

If it is possible, than we should use Bouncy Castle. Otherwise, we can continue using openssl . However, I would prefer to switch from pre-generated test resources to dynamically generated ones where it is feasible.

What do you think?

Kind Regards,
Alex

**Comment by vavrtom** [comment]
Hi Alex,

generating certificates lasts about 10 - 15 seconds on i5-4570. It looks like Bouncy Castle supports generating CRLs (https://www.bouncycastle.org/wiki/display/JA1/X.509+Certificate+Revocation+Lists), I guess it should be possible to generate all test certificates.

I think it is good idea to use Bouncy Castle, but I suggest to solve generating test certificates in different JIRA. I left generated certificates in repository for now. When generating by Bouncy Castle will be in place, test certificates can be removed from repository.

Changes done:
* certificates moved to qpid-test-utils
* data URLs are allowed for CRL file
* renamed attributes in AbstractTruststore and related files
* AuthenticationTest 
  * http server is based on jetty (I chose com.sun.net.httpserver.HttpServer because it is included in JVM)
  * if port is occupied, tests using http server are skipped
* removed KeystoreTestBase
* removed hardcoded separator from class TestSSLConstants
* doc book module updated

Best Regards,
Tomas

**Comment by alex-rufous** [comment]
Hi Tomas,
Thanks for addressing my review comments. My apologies for the delay with applying this pull request.

I have an additional question to the implementation of `org.apache.qpid.server.security.AbstractTrustStore#getParameters`. If attribute 'certificateRevocationListUrl' is set, the other certificate revocation check attributes are ignored. Why is that? I cannot find in documentation that `java.security.cert.PKIXParameters#addCertStore` and `java.security.cert.PKIXParameters#addCertPathChecker` are mutually exclusive. It looks like we should be able to add `PKIXRevocationChecker` together with not null CLR. Am I missing something here?

Kind Regards,
Alex

**Comment by vavrtom** [comment]
Hi Alex,

you are right, there is no need to ignore revocation check attributes when CRL file is set.

I modified code to always set revocation check attributes.

Best Regards,
Tomas

**Pull request closed without merging**
