### PR TITLE
Qpid-8374: [Broker-J][ACL] Allow case insensitive mapping of group members to groups in existing GroupProvider

### PR DESCRIPTION
**Pull request by RedFlashNinja**

### CODE REVIEW

**Comment by RedFlashNinja** [comment]
Let me to notice:
There were done some merges in Broker-J during the week.
After that it is not possible to build project using JDK11.

**Comment by alex-rufous** [comment]
Hi Stanislav,

I looked through the suggested changes and got the following review comments and questions:
* FileBasedGroupProviderImpl does not extend AbstractGroupProvider. It seems for consistency sake it has to follow the rest of group provider implementations and extend AbstractGroupProvider
* The default value for caseSensitive attribute in GroupProvider interface can be derived from context variable. I would like to add the context variable in GroupProvider interface as illustrated in a code snippet below:
`
String GROUP_PROVIDER_CASE_SENSITIVE = "qpid.groupProvider.caseSensitive";
@SuppressWarnings("unused")
@ManagedContextDefault(name = GROUP_PROVIDER_CASE_SENSITIVE)
String DEFAULT_GROUP_PROVIDER_CASE_SENSITIVE = "true";

@ManagedAttribute(defaultValue = "${" + GROUP_PROVIDER_CASE_SENSITIVE + "}", description = "Allow to choose CaseSensitive or CaseInsensitive search of Groups and Users")
boolean isCaseSensitive();
`
* In FileGroupDatabaseCaseInsensitiveTest the test fields are initialized in static block. Is there any reason not to use junit @BeforeClass and @AfterClass methods to perform the initialization and clean up of test suite resources?
* The same applies to FileGroupDatabaseTest; it seems initialization can be done @BeforeClass method and clean up in @AfterClass method.
* It seems that case sensitive search seems is not applicable to CloudFoundryDashboardManagementGroupProvider. I am actually thinking that adding caseSensitive attribute there would be a mistake, as it will have no meaning there. I think we need an intermediate interface for GroupProvider supporting case insensitive group mapping. I think that it would be better to move attribute caseSensitive into special GroupProvider interface and extend FileBasedGroupProvider and GroupProviderImpl from that interface. Whilst CloudFoundryDashboardManagementGroupProvider can continue to extend original GroupProvider interface. That means that we need to change the UI as attribute "caseSensitive" will no longer be a common attribute. What do you think?

**Comment by RedFlashNinja** [comment]
Hi Alex @alex-rufous, 
I want to discuss the last point you have described, please.
If Case Sensitive only applied to GroupFile type  it is better to replace new variable into FileBasedGroupProvider.
There will be 2 attributes: "path" & "caseSensitive".
And UI will be changed accordingly.

**Comment by alex-rufous** [comment]
> Hi Alex @alex-rufous,
> I want to discuss the last point you have described, please.
> If Case Sensitive only applied to GroupFile type it is better to replace new variable into FileBasedGroupProvider.
> There will be 2 attributes: "path" & "caseSensitive".
> And UI will be changed accordingly.

Hi Stanislav,
There are two implementations of GroupProvider interface where case insensitive group mapping can be used:
- GroupFile (FileBasedGroupProviderImpl)
- ManagedGroupProvider (GroupProviderImpl)

Potentially, you can duplicate the changes in both implementations. Alternatively,  you can implement changes in abstract class and extend corresponding implementations from that class. The latter seems a better approach from clean code point of view. You can start with a duplicate code and refactor the common code into a separate class later. I usually implemented my code in the way where the first implementation is "dirty"; I try to refactor the code to make it clean before commit.

I would like to point out that FileBasedGroupProviderImpl should be deprecated (on some point in future) and removed from the Broker together with authentication providers implementing interface ExternalFileBasedAuthenticationManager (PlainPasswordFile, Base64MD5PasswordFile). 

Thus, FileBasedGroupProviderImpl can be left unchanged and the corresponding changes can be only added into GroupProviderImpl.

As you have already added the relevant changes into both implementations, I though it would be  easier just to keep the changes for FileBasedGroupProviderImpl.

Regarding UI: for simplicity, you can duplicate the changes in UI for both providers. Otherwise, the UI might get more complicated than it should be. We can discuss the possible UI  refactoring later.

One review comment I have forgotten to mention previously:  FileBasedGroupProviderImpl might need to have some logic around changing the value of caseSensitive attribute from managed interfaces (REST, AMQP management). With the implemented approach, the underlying database object needs to be recreated on changes to "caseSensitive". Alternatively, you can pass a reference to FileBasedGroupProvider interface into database implementation and call method isCaseSensitive() to perform the right look-up.

Kind Regards,
Alex

**Comment by RedFlashNinja** [comment]
Hi Alex @alex-rufous,
I have one more question about  CloudFoundaryDashboardManagement.

**code(cloudfoundarydashboardmanagement/show.js):**
_var table = query(".serviceToManagementGroupMappingTable", this.containerNode)[0];
console.log("Check 1: " + table);
table.innerHTML = tableContent;
console.log("Check 2: " + tableContent);
console.log("Check 3: " + table);_

**Opening GroupProvider panel for CloudFoundary I can see console output below:
(at 1st moment table is undefined). Should I leave it as it is?**   
_Check 1: undefined show.js:48:25
TypeError: table is undefined
show.js:49:17
Check 1: [object HTMLTableElement] show.js:48:25
Check 2: <tr><td>1</td><td>: new</td></tr>
<tr><td>2</td><td>: new_2</td></tr>
show.js:50:25
Check 3: [object HTMLTableElement]_

**Comment by alex-rufous** [comment]
> Hi Alex @alex-rufous,
> I have one more question about CloudFoundaryDashboardManagement.
> 
> **code(cloudfoundarydashboardmanagement/show.js):**
> var table = query(".serviceToManagementGroupMappingTable", this.containerNode)[0];
> console.log("Check 1: " + table);
> table.innerHTML = tableContent;
> console.log("Check 2: " + tableContent);
> console.log("Check 3: " + table);
> 
> **Opening GroupProvider panel for CloudFoundary I can see console output below: (at 1st moment table is undefined). Should I leave it as it is?**
> Check 1: undefined show.js:48:25
> TypeError: table is undefined show.js:49:17
> Check 1: [object HTMLTableElement] show.js:48:25
> Check 2: 1: new2: new_2 show.js:50:25
> Check 3: [object HTMLTableElement]
> 
> Thank you.
> Best Regards,
> Stanislav

Hi Stanislav,
It is an existing defect in cloudfoundary dashboard management UI.
It is caused by asynchronous loading and parsing of HTML template for the tab.
The method #update() can be called before the loading of template is completed. As result, the query cannot find the node with class 'serviceToManagementGroupMappingTable'. 
It could be fixed by checking the query output. The  innerHTML should be set only  when query returns node object.

Kind Regards,
Alex

**Comment by alex-rufous** [comment]
Hi Stanislav,
Here some review comments on  changes in FileGroupDatabaseCaseInsensitiveTest/FileGroupDatabaseTest:

- Setting constant variables in @BeforeClass is unnecessary complication. The user and group test data seems are constants and should remain declared as constant. The reason why I asked to introduce @BeforeClass/@AfterClass methods is just to remove test files immediately after the test
- I noticed that call to `UTIL.writeAndSetGroupFile(...)` is followed by `FILE_GROUP_DATABASE.setGroupFile(GROUP_FILE)` in some test cases.  That seems unnecessary as `FileGroupDatabase#setGroupFile` is called inside `UTIL.writeAndSetGroupFile()`
- There is no need to catch IOException in @BeforeClass and re-throw it as RuntimeException. Please change the method to throw Exception from  @BeforeClass

**Comment by RedFlashNinja** [comment]
Hi Alex, 
Do you want me to remove @BeforeClass and leave it as it was?

**Comment by alex-rufous** [comment]
> Hi Alex,
> Do you want me to remove @BeforeClass and leave it as it was?
Stanislav,
I actually prefer to keep @Before/@After annotations, as the test suites create temporary files to store group mapping and delete those files immediately at the end of running test suite.

**Pull request closed without merging**
